services:
  db:
    image: postgres:16
    container_name: social_network_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: social_network_java
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: balabol
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d social_network_java"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: social_network_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: social_network_java
      DB_USER: postgres
      DB_PASSWORD: balabol
    ports:
      - "8080:8080"

volumes:
  postgres_data:
